services:
  fluxgym:
    image: thelocallab/fluxgym-flux-lora-training
    container_name: fluxgym
    ports:
      - 7860:7860
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - DOWNLOAD_MODELS=true
    volumes:
      - /mnt/user/appdata/fluxgym:/app/fluxgym
    stop_signal: SIGKILL
    tty: true
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: all
            capabilities: [gpu]
    restart: unless-stopped
